version: '3.7'
services:
  mongodb:
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - '27017:27017'
    logging:
      driver: 'none'

  back:
    ports:
      - '3000:3000'

  ue_admin:
    build: ./ue_admin
    ports:
      - '3840:80'
    dns:
      - 223.6.6.6
      - 223.5.5.5

  ue_mongo:
    build: ./ue_mongo
    ports:
      - '3830:80'
    dns:
      - 223.6.6.6
      - 223.5.5.5
